version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    environment:
      - POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pb_config.json:/pb/pb_config.json
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public

volumes:
  pocketbase_data:
  pocketbase_public: 